'use strict';
var PICTURES_NUMBER = 25;
var MIN_LIKES = 15;
var MAX_LIKES = 200;
var MESSAGES = ['Всё отлично!', 'В целом всё неплохо. Но не всё.', 'Когда вы делаете фотографию, хорошо бы убирать палец из кадра. В конце концов это просто непрофессионально.', 'Моя бабушка случайно чихнула с фотоаппаратом в руках и у неё получилась фотография лучше.', 'Я поскользнулся на банановой кожуре и уронил фотоаппарат на кота и у меня получилась фотография лучше.', 'Лица у людей на фотке перекошены, как будто их избивают. Как можно было поймать такой неудачный момент?'];
var NAMES = ['Миша', 'Наташа', 'Соня', 'Маруся', 'Саша', 'Лёва'];
var pictureTemplate = document.querySelector('#picture').content.querySelector('a');
var pictureBlock = document.querySelector('.pictures');
var FILTER = ['(', '(', '(', '(', '(', '('];
window.appendPictures(pictureBlock, pictureTemplate, PICTURES_NUMBER, MIN_LIKES, MAX_LIKES, MESSAGES, NAMES);
window.makePicture(FILTER);
